reading config from file for logitechr400
shadow-robot/sr-teleop pull request #50
Opened 2019-03-12 13:07 UTC by mikramarc

2019-03-12 14:13 UTC, toliver requested changes

2019-03-12 14:13 UTC, toliver commented on logitech_r400/src/logitech_r400/logitech_r400
> +        self.product = int('0x' + str(config['product']), 16)
Please we should stick to our convention of using leading underscore for the member fields.

2019-03-12 14:15 UTC, toliver commented on logitech_r400/src/logitech_r400/logitech_r400
> +        self.product = int('0x' + str(config['product']), 16)
Also, please declare all the class member fields in the constructor.
This is a convention we should always follow.
It makes it possible to see the member fields in a glimpse.
You can initialise them to `None` if the values isn't known yet.

2019-03-12 14:17 UTC, toliver requested changes

2019-03-12 14:17 UTC, toliver commented on logitech_r400/src/logitech_r400/logitech_r400
> -R400_ID_PRODUCT_2 = 0xc538
Can we add all the known values to the yaml file and then check all of them?
As it is we are forcing the user to "debug" in order to find the IDs that we already know can be associated to the R400

2019-03-12 14:31 UTC, mikramarc commented on logitech_r400/src/logitech_r400/logitech_r400
> +        self.product = int('0x' + str(config['product']), 16)
Only did that because of other methods in the class, didn't see the bottom ones had different convention. Both comments fixed in 7b83e2b.

2019-03-14 09:43 UTC, toliver requested changes

2019-03-14 09:43 UTC, toliver commented on logitech_r400/src/logitech_r400/logitech_r400
> +        pointer._read_data()
If read_data is used in the main, it means it is a public method. Therefore it should not have a leading underscore.

2019-03-14 09:43 UTC, toliver commented on logitech_r400/src/logitech_r400/logitech_r400
> +        self.product = None
Product and vendor are private members, so they should have a leading underscore (like the ones above).

2019-03-14 09:43 UTC, toliver commented on logitech_r400/src/logitech_r400/logitech_r400
> +        pointer._read_data()
Also here.

2019-03-14 15:35 UTC, toliver requested changes

2019-03-14 15:35 UTC, toliver commented on logitech_r400/src/logitech_r400/logitech_r400
> +            self.configs = yaml.load(stream)
You have declared `self._config` in the constructor, but you are not using it here. You are declaring a different member.

2019-03-14 15:35 UTC, toliver commented on logitech_r400/config/config.yaml
> +version_0:
If you are using names like version_0, version_1 and so on, it means that this should be a vector, not a dictionary.

2019-03-14 15:35 UTC, toliver commented on logitech_r400/README.md
> +Information based on the following [wiki](http://www.tincantools.com/wiki/Accessing_Devices_without_Sudo).
You should also add a section to tell the user to check the config.yaml and make sure the Product and Vendor of their pointer are declared in the yaml.

2019-03-14 15:43 UTC, toliver requested changes

2019-03-14 15:43 UTC, toliver commented on logitech_r400/src/logitech_r400/logitech_r400
> +            if (dev.idVendor == int('0x' + str(config['vendor']), 16) and
You might do this more easily by defining the yaml parameter as a hexadecimal number:

```yaml
  product: 0x0e00
  vendor: 0x0111
```

Then this is simply:

```python
if (dev.idVendor == config['vendor']) and
```

2019-03-15 14:40 UTC, toliver approved these changes

2019-03-15 14:40 UTC, merged