F#src 3193 merge mocks
shadow-robot/sr-teleop pull request #52
Opened 2019-06-06 15:01 UTC by carebare47

2019-06-07 10:52 UTC, mikramarc requested changes

2019-06-07 10:52 UTC, mikramarc commented on cyberglove_trajectory/src/cyberglove_trajectory/cyberglove_mock.py
> +class VRCodes:
this is not used

2019-06-07 10:52 UTC, mikramarc commented on cyberglove_trajectory/src/cyberglove_trajectory/cyberglove_mock.py
> +    def trigger_press(self):
neither are those :)

2019-06-07 10:52 UTC, mikramarc commented on cyberglove_trajectory/src/cyberglove_trajectory/cyberglove_mock.py
> +                #self.trigger_press()
please remove commended out code

2019-06-07 10:52 UTC, mikramarc commented on cyberglove_trajectory/src/cyberglove_trajectory/cyberglove_mock.py
> +            #self.trigger_release()
and here

2019-06-07 10:52 UTC, mikramarc commented on cyberglove_trajectory/src/cyberglove_trajectory/cyberglove_mock.py
> +                rospy.loginfo("SPAM")
remove spam :P

2019-06-07 10:52 UTC, mikramarc commented on cyberglove_trajectory/src/cyberglove_trajectory/cyberglove_mock.py
> +    def _publish_button_event(self, device_id, button_id, event_id, device_type, device_index):
not used

2019-06-07 10:52 UTC, mikramarc commented on cyberglove_trajectory/src/cyberglove_trajectory/cyberglove_mock.py
> +        self._hand_traj_client = actionlib.SimpleActionClient('/sr_teleop_vive_cyberglove_trajectory_controller' +
this should really be `"rh_trajectory_controller/follow_joint_trajectory"` by default. Only when running it for teleop, we should remap that to this value, like is being done here https://github.com/shadow-robot/sr_teleop_demos/blob/kinetic-devel/sr_teleop_vive_cyberglove/launch/cyberglove.launch#L9

Guess you should just parametrize it and in the top level mock for teleop overwrite to proper value.

2019-06-07 10:57 UTC, mikramarc commented on cyberglove_trajectory/src/cyberglove_trajectory/cyberglove_mock.py
> +        self._hand_traj_client = actionlib.SimpleActionClient('/sr_teleop_vive_cyberglove_trajectory_controller' +
Also, you will have to change that default here:
https://github.com/shadow-robot/sr_teleop_demos/pull/47/files#diff-548d6b3dbc683e6303cde66c0ff034f7R19

2019-06-07 11:54 UTC, carebare47 commented on cyberglove_trajectory/src/cyberglove_trajectory/cyberglove_mock.py
> +class VRCodes:
done

2019-06-07 11:54 UTC, carebare47 commented on cyberglove_trajectory/src/cyberglove_trajectory/cyberglove_mock.py
> +    def trigger_press(self):
done

2019-06-07 11:54 UTC, carebare47 commented on cyberglove_trajectory/src/cyberglove_trajectory/cyberglove_mock.py
> +                #self.trigger_press()
done

2019-06-07 11:54 UTC, carebare47 commented on cyberglove_trajectory/src/cyberglove_trajectory/cyberglove_mock.py
> +            #self.trigger_release()
done

2019-06-07 11:54 UTC, carebare47 commented on cyberglove_trajectory/src/cyberglove_trajectory/cyberglove_mock.py
> +                rospy.loginfo("SPAM")
Really? :(

2019-06-07 11:54 UTC, carebare47 commented on cyberglove_trajectory/src/cyberglove_trajectory/cyberglove_mock.py
> +    def _publish_button_event(self, device_id, button_id, event_id, device_type, device_index):
done

2019-06-07 11:56 UTC, mikramarc requested changes

2019-06-07 11:56 UTC, mikramarc commented on cyberglove_trajectory/src/cyberglove_trajectory/cyberglove_mock.py
> +import argparse
unused

2019-06-07 11:56 UTC, mikramarc commented on cyberglove_trajectory/src/cyberglove_trajectory/cyberglove_mock.py
> +import rospkg
unused

2019-06-07 11:56 UTC, mikramarc commented on cyberglove_trajectory/src/cyberglove_trajectory/cyberglove_mock.py
> +import sys
unused

2019-06-07 15:57 UTC, mikramarc approved these changes

2019-06-07 15:59 UTC, mikramarc requested changes

2019-06-07 15:59 UTC, mikramarc commented on cyberglove_trajectory/src/cyberglove_trajectory/cyberglove_mock.py
> +        self._cycle_hand_positions = cycle_hand_positions
If this is set to false, the node will do nothing at the moment. Should we just remove that param?

2019-06-11 11:24 UTC, mikramarc approved these changes

2019-06-11 12:14 UTC, mikramarc approved these changes

2019-06-20 19:01 UTC, merged